name: CI

on:
  push:
    branches:
    - develop
    - master
  pull_request:
    branches:
    - develop
    - master

jobs:
  python-ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    name: CI workflow
    steps:
      - name: checkout source repo
        uses: actions/checkout@v2      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Installs dependencies"
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          # Install build deps
          pip install setuptools pytest pytest-cov flake8 ipython
          # Install the package from setup.py
          pip install .
      - name: linting flake8
        run: |
          flake8